version: '2'
services:
  web:
    build:
      context: './modules/web/'
      dockerfile: 'Dockerfile.dev'
    command: sh -c 'nodemon server-assets/server.js'
    volumes:
      - ./modules/web/build:/usr/proj/build
      - /usr/proj/node_modules
    links:
      - redis
    ports:
      - '9999:8000'
  redis:
    image: redis:3.0
